 <span class="boldtext">1. How do I installed eGamer onto my wordpress blog? </span>
<div class="indent">
  <p>There are several files included in the ZIP folder. These include wordpress theme files, plugin files, and photoshop files. To installed your wordpress theme you will first need to upload the theme/plugin files via FTP to your server. </p>
  <p>First you are going to upload the theme folder. Inside the ZIP folder you downloaded you will see a folder named &quot;theme.&quot; Within it is a folder named &quot;eGamer.&quot; Via ftp, upload the &quot;eGamer&quot; folder to your Wordpress themes directory. Depending on where you installed Wordpress on your server, the wp themes folder will be located in a path similar to: /public_html/blog/wp-content/themes. </p>
  <p>Next you need to upload the plugin files. Inside the zip folder you downloaded there will be a folder named &quot;plugin.&quot; Within this folder are several other files and folders which need to be uploaded to your Wordpress plugins directory. This directory will be located at /public_html/blog/wp-content/plugins. Once you have the plugins uploaded you will need to activate them via your Wordpress control panel. Login to your wordpress admin area and click on the &quot;plugins&quot; link. Activate the following plugins: Wp Page Navi.</p>
  <p>Next you need to select eGamer and make it your default theme. Click on the design link, and under the themes tab locate eGamer from the selection of themes and activate it. Your blog should now be updated with your new theme. </p>
</div>
<span class="boldtext">2. How do I add the thumbnails to my posts? </span>
<div class="indent">
  <p>eNews utilizes a script called TimThumb to automatically resize images. Whenever you make a new post you will need to add a custom field. Scroll down below the text editor and click on the &quot;custom fields&quot; link. In the &quot;Name&quot; section, input &quot;Thumbnail&quot; (this is case sensitive). In the &quot;Value&quot; area, input the url to your thumbnail image. Your image will automatically be resized and cropped. The image must be hosted on your domain. (this is to protect against bandwidth left) </p>
  <p><span class="style1">Important Note: You <u>must</u> CHMOD the &quot;cache&quot; folder located in the eNews directory to 777 for this script to work. You can CHMOD (change the permissions) of a file using your favorite FTP program. If you are confused try following <a href="http://www.siteground.com/tutorials/ftp/ftp_chmod.htm"><u>this tutorial</u></a><u>.</u> Of course instead of CHMODing the template folder (as in the tutorial) you would CHMOD the &quot;cache&quot; folder found within your theme's directory. </span></p>
</div>
<span class="boldtext">3. How do I add my title/logo? </span>
<div class="indent">In this theme the title/logo is an image, which means you will need an image editor to add your own text. You can do this by opening the blank logo image located at Photoshop Files/logo_blank.gif, or by opening the logo PSD file located at Photoshop Files/logo.psd. Replace the edited logo with the old logo by placing it in the following directory: theme/eNews/images. If you need more room, or would like to edit the logo further, you can always do so by opening the original fully layered PSD file located at Photoshop Files/eNews.psd  </div>
<span class="boldtext">4. What's with the reviews/ratings section on the homepage? How does it work? </span>
<div class="indent">
  <p>This theme was made for gaming sites, but it certainly can be used for whatever you like. However, because a lot of gaming websites like to review games I decided to input a basic author rating system. The recent reviews section can be turned off from within the theme's options menu, you are not required to add review posts. </p>
  <p>Whenever you make a post you can assign it a rating value. To do this create a custom field with the Name "rating" and a Value of how many stars you would like to give the post. Simply input any number between 0-5. (no decimals) Once you save your post a rating will appear on your post page as a star value. On the homepage, there is a section that displays recent reviews. This sections searchers through all your posts and gathers any post that has a rating assigned to it, and then displays the most recent 4 reviews in a descending fashion. </p>
  </div>
  <span class="boldtext">5. How do I add videos to my posts, and how does the Recent Videos section on the homepage work? </span>
  <div class="indent">
  <p>This theme can embed videos from other sources, but does not have a native video player. This means that you can only post videos that are taken from online video sources such as Youtube. When you make a new post you will need to add a custom field with the Key &quot;Video&quot; In the Value area just paste the embed code from your video host. For example, an embed code from youtube looks like this:</p>
  <p>&lt;object width=&quot;425&quot; height=&quot;344&quot;&gt;&lt;param name=&quot;movie&quot; value=&quot;http://www.youtube.com/v/WneDU-K3Sww&amp;hl=en&amp;fs=1&quot;&gt;&lt;/param&gt;&lt;param name=&quot;allowFullScreen&quot; value=&quot;true&quot;&gt;&lt;/param&gt;&lt;embed src=&quot;http://www.youtube.com/v/WneDU-K3Sww&amp;hl=en&amp;fs=1&quot; type=&quot;application/x-shockwave-flash&quot; allowfullscreen=&quot;true&quot; width=&quot;425&quot; height=&quot;344&quot;&gt;&lt;/embed&gt;&lt;/object&gt;</p>
  <p>You will notice that some video hosts try to add in links to their website, you probably want to delete these. All you need is the object and or embed codes. </p>
  <p class="style1">Important Note: There is a bug with the upgrade of WordPress 2.6 that adds random &quot;/&quot; to the embed code when you add it. For this reason you need to add the code twice. After you click &quot;Add Custom Field&quot; you will notice that the code in the value area refreshes and the &quot;/&quot; appear. After this occurs simply delete the embed code from the value area and paste in the original embed code again and then press the &quot;update&quot; button. If you don't do this the video won't show up. </p>
  Whenever you add a video to your post, using the method above, it will be displayed cleanly above your post content on single post pages. On the homepage there is a section called Recent Videos. This box searches through all your posts and gathers the ones that have a Video Custom Field assigned to them. It then displays the most recent video on the homepage. This section can be turned on and off from within the theme's options menu. </div>
  <span class="boldtext">6. How do I add my title/logo? </span>
  <div class="indent">In this theme, the title/logo is an image, which means you will need an image editor to add your own text. You can do this by opening the blank logo image located at Photoshop Files/logo.jpg, or by opening the logo PSD file located at Photoshop Files/logo.psd. Replace the edited logo with the old logo by placing it in the following directory: theme/eGamer/images. If you need more room, or would like to edit the logo further, you can always do so by opening the original fully layered PSD file located at Photoshop Files/eGamer.psd </div>

<span class="boldtext">7. How do I manage advertisements on my blog? </span>
<div class="indent">You can change the images used in each of the advertisements, as well as which URL each ad points to, through the custom option pages found in wp-admin. Once logged in to the wordpress admin panel, click &quot;Design&quot; and then &quot;Current Theme Options&quot; to reveal the various theme options. </div>

<span class="boldtext">8. Can I change how many recent posts are displayed on the homepage? </span>
<div class="indent">You sure can. The number of recent posts being displayed on the homepage can be changed at any time via the custom option pages in wp-admin. </div>

<span class="boldtext">9. How do I setup the Featured Articles on the homepage? </span>
<div class="indent">
  <p>The Featured Articles are pulled from a specific category. You can choose which category is used for the Featured Articles section via the Theme Options page in wp-admin. Under the General > Featured Articles section of ePanel (the elegant themes options page) you will see a dropdown menu where you can choose your featured articles category.</p></div>